### ISSUE TITLE
Current Todo

### ISSUE THREAD

**Issue by Trhod17** [CodersDownUnder/SlaughterCraftRewrite#4]
- [ ] add recipes for breaking down chicken into individual parts
- [ ] add recipes for cooking chicken parts in furnace
- [ ] add blood and bones fertilizer
- [ ] add/come up with advancements
- [ ] Finish chicken related things
- [ ] add/come up with foods made with chicken

**Comment by Trhod17** [comment]
- [ ] Finish chicken related things
- [ ] start on pig related things
